version: "3"

services:
  autotests:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: QACloudCamp
    volumes:
      - ./allure-results:/usr/project/allure-results
    command: pytest --alluredir=allure-results