version: "3"

services:
  autotests:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: QACloudCamp
    volumes:
      - ./allure_results:/usr/project/allure_results
    command: pytest --alluredir=allure_results