name: QACloudCamp

on:
  push:
    branches:
      "main"
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose target
#        required: true
        default:
        type: choice
        options:
          -all_tests
          -smoke_tests
          -regression_tests

jobs:
  test:
  run-on: ubuntu-latest

  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: all_tests
      run: pytest
    - name: all_tests
      if: "github.event.inputs.deployment_target == 'all_tests'"
      run: pytest
    - name: smoke_tests
      if: "github.event.inputs.deployment_target == 'smoke_tests'"
      run: pytest -m smoke
    - name: regression_tests
      if: "github.event.inputs.deployment_target == 'regression_tests'"
      run: pytest -m regression

    - name: Get Allure history
      uses: actions/checkout@v2
      if: always()
#      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages
    - name: Build Allure report
      uses: simple-elf/allure-report-action@master
      if: always()
      with:
        allure_results: allure-results
        allure_history: allure-history
        keep_reports: 20
    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v2
      env:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: allure-history
